### PR TITLE
switch to script.src for old IE; fixes #3

### LINKED ISSUE #3: IE issues
From https://github.com/mathjax/MathJax/issues/1741

Seems like using `script.src` instead of `script.getAttribute('src')` should be sufficient.

### PR DESCRIPTION
**Pull request by pkra**

### CODE REVIEW

**Comment by dpvc** [comment]
LGTM

**Comment by pkra** [comment]
Deployed to GCS.

**Comment by pkra** [comment]
Changes coming through on the CDN.

**Comment by pkra** [comment]
Smoke tests look good.

**Pull request merged**
